### ISSUE TITLE
Feature request: always show underline

### ISSUE THREAD

**Issue by lonix1** [oreporan/color-tabs-vscode#1]
Nice job!

Would be even nicer if the colored underline would be visible all the time. The way it works now is it only shows the color when the tab is active.

**Comment by oreporan** [comment]
hey
Thanks :)

You mean on all open tabs? 
I figured the way most people work (or atleast I do) is that I don't actually navigate that much between tabs, I usually look for a specific file or click on a file from the explorer. 
What do you think?

**Comment by lonix1** [comment]
I guess different people work in different ways.
- The way I work - and I assume many others too - is I have a number of files (tabs) open at the same time
- It would be nice to "colorize" all the open tabs against a regex
- Then I can have client / server / config files open at the same time, and I can tell which is which

It's a nice plugin nonetheless, thanks!

**Comment by oreporan** [comment]
I guess we could make it configurable.
If you make a PR I'd put it in :)
Thanks for liking!

**Comment by lonix1** [comment]
I've never done VSCode plugins, wouldn't even know where to start :laughing: 
In time I'm sure others will find this plugin and help out!
It's very useful as it is, I like it. Thanks.

**Comment by hanimay** [comment]
:+1:

**Comment by sustained** [comment]
:+1: for this, I don't know anything about VS Code plugins either but maybe I'll look into it. I also really want this functionality.

**Comment by oreporan** [comment]
Unfortunately this functionality is not possible, the API only allows to control the color of the focused tab

**Comment by oreporan** [comment]
Unless someone has another solution...

**Comment by sustained** [comment]
Guess we need to bug Microsoft then.
