### ISSUE TITLE
Color packages in the file explorer

### ISSUE THREAD

**Issue by therenca** [oreporan/color-tabs-vscode#12]
....so that when I navigate through different files on the sidebar, I immediately know where to go as per the coloration....

**Comment by oreporan** [comment]
Hey
Not sure I understand as your issue isn't very clear.

If you're loking to change the color of the sidebar, this feature exists since version 6.0.0
You can see it [here](https://github.com/oreporan/color-tabs-vscode#060) 

The config is `colorTabs.activityBarBackground` = true

**Comment by therenca** [comment]
![image](https://user-images.githubusercontent.com/45092633/56138939-8c9cc080-5fa0-11e9-9ef4-835a841b4579.png)


  like so...

**Comment by oreporan** [comment]
oh you mean that the actual project files will be colored?

While I like this idea, it could become confusing. As many times people want a certain color for anything that is `web/*` which could appear in several packages. 
If your sidebar will begin looking too colorful it could be more confusing than helpful

**Comment by oreporan** [comment]
Here is a list of things that can be colored - 
If you find what you're looking for here, let me know

https://code.visualstudio.com/api/references/theme-color

**Comment by therenca** [comment]
https://github.com/Microsoft/vscode/issues/31308

Guys requested this feature some time back, but it has not yet been implemented, though you have done a great job helping us navigate easily within a workspace, the only thing remaining is if it could be an optional config on your extension, to allow for different coloration of different folders within the workspace, hence I would know the green section deals with front end, etc....

**Comment by oreporan** [comment]
@therenca 

Here is a list of "things" that can be colored - https://code.visualstudio.com/api/references/theme-color

However to color the package and its children, I *think* you would need to iterate over the files.
Its a bit more complicated than what I do now

If you make a PR we can go over it

**Comment by therenca** [comment]
okay, will see what I can do, thanks.

**Comment by oreporan** [comment]
Keep in mind that if you want all files to always be colored, that means on startup you need to iterate over all the files and match them with the regex, this may have a performance impact on big projects.

Maybe it should color only a project that has been clicked/expanded

**Comment by therenca** [comment]
yes, nice catch, expanded projects only
