### ISSUE TITLE
Incompatible with vscode 1.24.1

### ISSUE THREAD

**Issue by haoadoreorange** [oreporan/color-tabs-vscode#13]
Hello, 

I have an error today trying to install colorTabs: it's incompatible with vscode 1.24.1

**Comment by oreporan** [comment]
@babyadoresorange 
Are you able to see what the error is when trying to install?
Also `1.24.1` is 1 year old

**Comment by haoadoreorange** [comment]
@oreporan I just updated to 1.33.1, but I cannot have any feature. I already activated all of them.

`    "colorTabs.config": [
      {
        "regex": ".*\/src\/.*",
        "color": "#00FF00",
        "label": "SRC",
      }
    ],
    "colorTabs.activityBarBackground": true,
    "colorTabs.titleLabel": true,
    "colorTabs.titleBackground": true`

with this I see no color at all.
Do you have an idea why ?

**Comment by oreporan** [comment]
try without escaping `.*\/src\/.*` -> `.*/src/.*`
Are you on a windows machine?

**Comment by haoadoreorange** [comment]
Hi, yes I'm on windows for now. Is there a difference ?
UPDATED: no success without escaping

**Comment by oreporan** [comment]
in windows you would need `.*\src\.*` I assume

**Comment by haoadoreorange** [comment]
@oreporan : I figured it out :+1: 
Is there somehow to color the tab even when its not active ? I did a quick search but did not find out even with extension API

**Comment by oreporan** [comment]
These are the available coloring options:

https://code.visualstudio.com/api/references/theme-color

However this would add a complication, in my experience only the current working file is interesting enough

**Comment by oreporan** [comment]
I'm going to go ahead and close this issue
feel free to make a separate feature request
