### ISSUE TITLE
Feature request: allow different colors for split editors

### ISSUE THREAD

**Issue by ian-h-chamberlain** [oreporan/color-tabs-vscode#14]
When the extension is active, all open tabs take on the color of the focused editor. I'm not sure if it's possible, but it would be nice if other visible tabs kept the color for their regex match (or no color if not matching anything) even when not focused.

Edit: looks like `tab.unfocusedActiveBorder` can be used for this purpose, although I don't know how it will behave with e.g. 3+ editor groups – I'm guessing all unfocused editor groups will have the same color. Perhaps it would be better just to set the unfocused color to nothing, and only color the focused tab.

Example `.vscode/settings.json`
```
{
    "colorTabs.config": [
        {
            "regex": "foo",
            "color": "#ff0000",
            "label": "foo"
        },
        {
            "regex": "bar",
            "color": "#00ff00",
            "label": "bar"
        }
    ]
}
```

`foo` focused:
![Screen Shot 2019-04-25 at 11 17 19](https://user-images.githubusercontent.com/11131775/56747346-ca8da780-674b-11e9-8f35-56e2a864f636.png)

`bar` focused:
![Screen Shot 2019-04-25 at 11 17 24](https://user-images.githubusercontent.com/11131775/56747347-ca8da780-674b-11e9-83b5-d9a10cae90ab.png)

Ideally, in both screenshots the `foo` tab would have a red underline, while `bar` would have a green one. The status bar behavior does not need to change.

**Comment by oreporan** [comment]
This looks like a bug, it should not be coloring inactive tabs at all.

Does this happen to you only when working in a split view mode?

**Comment by ian-h-chamberlain** [comment]
Yes, the inactive tabs within an editor group are always uncolored, but inactive editor groups still color the border of the active tab.

VScode Version 1.33.1 (1.33.1)
Extension information:
Name: ColorTabs
Id: orepor.color-tabs-vscode-ext
Description: changes the active tab/status-bar/title-background color based on regex
Version: 0.6.0
Publisher: Ore Poran
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext

**Comment by oreporan** [comment]
Ah I see, I guess according to vscode, both tabs are "active" which is why coloring one, automatically colors the other...
I'm not sure its capable of differentiating groups. I'll check

**Comment by oreporan** [comment]
yeah `unfocusedActiveBorder ` could work if I set it to null

**Comment by oreporan** [comment]
so whats happening is that by default, the `unfocusedActiveBorder` is being set when `activeTabBorder` is changed. 
Setting `unfocusedActiveBorder ` to null doesn't do anything because it defaults again to the same color as `activeTabBorder`.
There is no way that I found, to set `unfocusedActiveBorder` to its default color, and giving it the correct color (according to the regex) is also not available according to what I saw, because I only have access to the opened file. 

Any ideas?

**Comment by ian-h-chamberlain** [comment]
According to [this stackoverflow post](https://stackoverflow.com/questions/47117621/how-to-get-the-vscode-theme-color-in-vscode-extensions) you should be able to get a reference to the existing workbench setting for `unfocusedActiveBorder` – then can you use that to set it instead of `null`? I'm not too familiar with the VSCode API but it seems like that might give you enough information to explicitly set it back to the default value?

**Comment by oreporan** [comment]
According to the issue related to the post, its impossible to get the color from the `workspace.colorCustomizations` programatically , which is where its being set...
Also if you switched between editors, wouldn't that set the wrong color in the newly unfocused tab?

**Comment by ian-h-chamberlain** [comment]
Hmm... it seems you are correct. I noticed you filed https://github.com/Microsoft/vscode/issues/72887 and someone just responded with this suggestion:
```
"tab.unfocusedActiveBorder": "#fff0",
```

From testing it in my workspace settings it seems to have the desired effect, although I suppose it's a bit of a hack. But, pending a real API to get the default color, it works for me. It may not be desirable to hardcode such a value into the extension but I can use it as a workaround for now. Thanks for looking into this!
