### ISSUE TITLE
Doesn't seem to work with display names

### ISSUE THREAD

**Issue by BasvanH** [oreporan/color-tabs-vscode#18]
Hi,

My environment:
```
Version: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393
```

I've configured Color Tabs like so:
```
    "colorTabs.config": [
        {
            "regex": ".*\/MyDev1\/.*",
            "color": "#FF0000"
        },
        {
            "regex": ".*\/folder3\/.*",
            "color": "#333300"
        }
    ],
    "colorTabs.titleBackground": true,
    "colorTabs.activityBarBackground": true,
    "colorTabs.titleLabel": true
```

I have a workspace with two nested folders which root has a name property set in the workspace:
```
{
	"folders": [
		{
			"path": "D:\\folder1\\folder2\\folder3",
			"name": "MyDev1"
		},
		{
			"path": "D:\\folder4\\folder5\\folder6",
			"name": "MyDev2"
		},
      ]
}
```

Color tabs doesn't seem to trigger on both. Any idea why?

Regards,
Bastiaan

**Comment by oreporan** [comment]
@BasvanH 

what exactly is the "name" in the folders object?
Is `MyDev1` a file name ?

I don't understand this:
> ...which root has a name property set in the workspace

With this setup:

![Screen Shot 2019-05-27 at 11 05 31](https://user-images.githubusercontent.com/2146999/58408992-683c0580-806f-11e9-89f3-b756ef5424ac.png)

and this config (on mac):

```json
   "colorTabs.config": [
        {
          "regex": ".*/folder3/.*",
          "color": "#ff007f",
        }
      ]
```

Everything works fine

Usually if something doesn't work its your Regex (Check it on [https://regexr.com](https://regexr.com))

**Comment by BasvanH** [comment]
@oreporan , the name property changes the display name of the folder in the workspace tree view:
![image](https://user-images.githubusercontent.com/1708136/58409527-8a825300-8070-11e9-8b0f-08b76bea4614.png)

So `MyDev1` is a display name of `folder3`

Perhaps it's the regex?  In windows the folder names are `\\foldername\\`

**Comment by oreporan** [comment]
Ah interesting, didn't know about this feature.
Let me test it locally

**Comment by oreporan** [comment]
Also works for me.

Your regex is wrong, similar issue here #6

**Comment by BasvanH** [comment]
Got it working based on the folder names, but not based on the display names.

Working:
```
{
  "regex": "folder3\\.*",
  "color": "#0099ff"
},
```
Not working:
```
{
  "regex": "MyDev1\\.*",
  "color": "#0099ff"
},
```

**Comment by oreporan** [comment]
Yeah, thats because we only at the file path, not at the display name.
You're welcome to make a PR for this support
