### ISSUE TITLE
Colour the actual tab

### ISSUE THREAD

**Issue by Samywamy10** [oreporan/color-tabs-vscode#19]
I'm not sure if this is possible, but I'd really like to be able to colour the actual tab - so when I'm not in that tab I can quickly see the colours of all the other tabs. I've done a quick mockup to describe what I mean.

![image](https://user-images.githubusercontent.com/1314053/60558148-8215ea00-9d8b-11e9-8e26-123762f15a27.png)

**Comment by oreporan** [comment]
Hey
This has been addressed in #1 
Its not possible to color any other tab than the focused one using vscode-api

**Comment by Samywamy10** [comment]
Thanks, just read that. I looked into creating my own PR today and ran into the same limitations (you can only customise borders of ALL tabs or the active tab). Disappointing because this would be super useful. Thanks anyway!
