### ISSUE TITLE
Feature Request: Windows path auto-conversion

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [oreporan/color-tabs-vscode#20]
Requesting a feature to auto convert "/" to "\\" once Windows operating system is detected. It'd be useful if developing/writing cross-platform.

**Comment by oreporan** [comment]
Hey
I'm not sure thats something you want to be doing automatically. 
This is a workspace setting, so by definition - you know what OS your workspace is running on. Am I wrong?

**Comment by Turgon-Aran-Gondolin** [comment]
Sorry if I didn't make myself clear. That's say I just created a project in Github, and I want to edit it from both a Linux and a Windows PC. After cloned it it's natural to set the path as the repo name. So I have `Settings sync` extension on, that makes me be able to sync this path in both PCs. Since the repo name is always the same, it doesn't matter which OS I'm in. But the slashes does matter when I try to do this. If `colortab` can't convert slashes for me, I'll have to edit the setting everytime I sync. This really makes the whole syncing thing pointless. 

I'm not sure why you think it's a bad idea, is it because you worry that there might be slashes in the filename? I'm quite sure Windows won't allow that, but I'm less certain with Linux. (Personally I'd never name a file like that so I never thought about it.)

**Comment by oreporan** [comment]
Hmm ok. I see your point, but wouldn't it still be possible to just duplicate the colorTabs settings once? Like:

```
mobile/something/* -> red 
mobile\something\* -> red 
```

**Comment by Turgon-Aran-Gondolin** [comment]
Fair point. Still, it might be more convenient if we don't have to duplicate it every time we add a new repo, and with a cleaner config file I think. Also if we want to change the color, it'd be nice to just change one line instead of two. Is it possible to add an option so people like me can choose to auto-convert it and others don't have to be forced upon? 

In the meantime, I'll take your advice and duplicate it. Thanks for that.

**Comment by oreporan** [comment]
How would you suggest to do it? The plugin could detect OS and run the regex OS-agnostic. However I'd rather not have too much magic happen without the user understanding why...

**Comment by Turgon-Aran-Gondolin** [comment]
I'm thinking put an option like `colorTabs.convertslash` or something like that and set it to `false` by default. If it's true then run the detectOS&conversion before input the path regex into your original routine. Then I think normal users won't be affected and users like me is happy. But I don't know how complicated is this and how many people would want this, and you probably think way ahead of me so it's totally your call.

**Comment by oreporan** [comment]
At this point I'm not planning to add another configuration.
Closing this for now.
