### ISSUE TITLE
Feature request: what to match

### ISSUE THREAD

**Issue by ghost** [oreporan/color-tabs-vscode#26]
Hi,
Great app (I hope one day we could change the icon color in the taskbar (Windows 10)).

I have a feature request:
I would like to choose what the regex is matched against.
For example, I would like to match my regex only on the root folder name (and not path) to ensure that my workspace doesn't change its color while changing tab.
Ideally, for each regex, I could give a string containing variables like the one given for the setting `window.title`.

example :
```json
"colorTabs.config": [
    {
        "regex": ".*\/node_modules\/.*",
        "against": "${activeFolderMedium}",
        "color": "#FF0000",
        "label": "Back off"
    },
    {
        "regex": ".*\/dirty\/.*",
        "against": "${dirty}",
        "color": "#00FF00"
    },
    {
        "regex": ".*\/desktop\/.*",
        "against": "${rootName}",
        "color": "#0000FF"
    }
]
```

**Comment by oreporan** [comment]
thanks @PierreMacherel 

I'm confused as to what exactly you're trying to achieve. 
If we look at 
```js
 {
        "regex": ".*\/node_modules\/.*",
        "against": "${activeFolderMedium}", // MyFolder/MySubFolder
        "color": "#FF0000",
        "label": "Back off"
    },
```

Right now the logic could be seen as - 
```js
 {
        "regex": ".*\/node_modules\/.*",
        "against": "${activeEditorMedium}", // MyFolder/MySubFolder/myFile.js
        "color": "#FF0000",
        "label": "Back off"
    },
```

>... to ensure that my workspace doesn't change its color while changing tab.

In what case would this happen between the sets of JSONs above? Only in the case that the file name is part of your regex. 
Maybe you can provide an example with some file names..

Other than that - as far as I know, extensions can not interpolate these settings from `windows.title`, it has to be done use the vscode API

**Comment by ghost** [comment]
There are some cases where that might be interesting:
- the dirty case
- match against the workspace name (or root folder) only. This one is the most useful for me: I want a color fixed for one workspace). In a workspace `Foo`, if a file is open, but outside of Foo, then the workspace lose its color.
    Moreover, if the file `/Bar/Foo/Baz.txt` is open in the workspace `/Bar`, with the following settings:
    ```json
    "colorTabs.config": [
        {
            "regex": ".*Foo.*",
            "color": "#color1"
        },
        {
            "regex": ".*Bar.*",
            "color": "#color2"
        }
    ]
    ```
    My I want the color of my workspace to be `#color1`, but it will be `#color2` (still in the case where I want to fix my workspace color for good).
    I could do `"regex": "^Bar.*"`, but for some reason, I cannot match the workspace name (I might open an issue for that later).
    So it would be easier to match only the workspace name.

**Comment by oreporan** [comment]
You're speaking about a color per workspace, am I assuming that you have multiple workspaces in the same vscode instance?
Because you can set a color per workspace if you use `workspace.settings`

In your example, you could try `^/Bar.*`

> match against the workspace name (or root folder) only. This one is the most useful for me: I want a color fixed for one workspace).

Why would you want a constant color? You don't need regex for this, just color your workspace..

**Comment by ghost** [comment]
I should not do feature request at the middle of the night :)
You are completely right, it is enough to do it on `workspace.settings`.
Sorry for the trouble.
