### ISSUE TITLE
Feature request: test on setting change

### ISSUE THREAD

**Issue by ghost** [oreporan/color-tabs-vscode#27]
Hi,
Would it be possible to trigger the test for changing color on setting change (or file save) so that I can test my settings immediately without having to change a tab ?

**Comment by oreporan** [comment]
To "trigger" requires a file to trigger against (to match a regex), in your case, the current file would always be `settings.json` because you just changed the setting...

If I did listen to `onSave`, aside from the redundant runs, how would anything change?

**Comment by ghost** [comment]
I will use your extension mostly for giving a color for each window / workspace. If you do the issue https://github.com/oreporan/color-tabs-vscode/issues/26, then it makes sense: the color would not depend on the active file. Sorry, I should have been more explicit.

**Comment by oreporan** [comment]
This extension also exists if you prefer to have a color per window- https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock

**Comment by ghost** [comment]
Thank you very much !
