### ISSUE TITLE
Feature request: ignore case

### ISSUE THREAD

**Issue by ghost** [oreporan/color-tabs-vscode#28]
Hi,
Could you add a setting (per regex) to ignore case ?

**Comment by oreporan** [comment]
While I agree it makes sense, since we are speaking about folder names (most likely) which have some conventions, don't you think covering it in a regex is enough? like `.*/[w|W]eb/.*`

**Comment by oreporan** [comment]
by the way - thanks for all the issues/requests :)

**Comment by ghost** [comment]
Thank you for this extension (I looked something like it for a year) :)

For this case, you can indeed do it with `.*/[w|W]eb/.*`, but in my case, I don't know in advance what will be the case for the folder name (for example, someone forked a repo, and changed the case (among others this)). I could indeed do `.*/[w|W][e|E][b|B]/.*`, but it isn't readable, and not practical for a long name.

**Comment by oreporan** [comment]
Yes I understand.
While I think this is a very small use case, I guess there is no harm in adding it as a configuration.

**Comment by oreporan** [comment]
Available in version `0.9.0`
Thanks!
