### ISSUE TITLE
#feature Request: Update Label

### ISSUE THREAD

**Issue by hanimay** [oreporan/color-tabs-vscode#3]
Lovely plugin.
Can we prepend or append the label with a title, when we mouse over the tab name ?
It's not easy to remember colors when working on multiple projects and I always find myself reading the whole URI of the file, So a label would make it much easier.
Thanks :)

**Comment by oreporan** [comment]
Hey, thanks :)

So apparently from what I checked, its impossible to change the tab name (weird)
Its according to this [stackoverflow question](https://stackoverflow.com/questions/45876887/change-title-of-untitled-tab-in-visual-studio-code)

We could do something in the titlebar though, would that be helpful?

**Comment by hanimay** [comment]
Not the tab itself but the label that shows up when you mouse over the tab.
Is that possible to change ?

**Comment by oreporan** [comment]
Unfortunately I couldn't find a way to edit the hover text of the tab

Here is a list of things you can change on the tab according to vscode - 

https://code.visualstudio.com/api/references/theme-color#editor-groups-tabs

**Comment by hanimay** [comment]
I see.
I did a quick look at the documentation, I think we can benefit from status bar to do that.
https://code.visualstudio.com/api/references/vscode-api#StatusBarItem
https://github.com/Microsoft/vscode-extension-samples/tree/master/statusbar-sample
What do you think ?

**Comment by oreporan** [comment]
to pop up a status bar every time you switch files?

**Comment by hanimay** [comment]
Ah no, check the sample, second link.

**Comment by oreporan** [comment]
I did :) 
I see a status bar that pops up to say how many lines you have - I assumed you mean to pup up this status bar to show some label?

**Comment by hanimay** [comment]
Ah ok :)
For me pop up is something that blocks my view .
Well it could always be visible 
![selection_004](https://user-images.githubusercontent.com/5787719/53431913-35e02500-39fa-11e9-9ad4-2cb3e48778a5.png)

**Comment by oreporan** [comment]
I'm not sure its a good idea to add another status bar
How about using the title bar for this? I already color it based on the regex, could also at a label - 

Currently its - `${activeEditorShort}${separator}${rootName}`

We could change it to -  `${regex_based_label}${separator}${activeEditorShort}${separator}${rootName}`

**Comment by hanimay** [comment]
I had the impression that we can't do it . 
The title bar would be amazing :+1:

**Comment by oreporan** [comment]
Check it out - Let me know what you think

https://github.com/oreporan/color-tabs-vscode/pull/4

**Comment by oreporan** [comment]
Released in `5.0.0`
