### ISSUE TITLE
Feature Request:  Allow theme to change based on regex

### ISSUE THREAD

**Issue by nate-whil** [oreporan/color-tabs-vscode#30]
I love this extension and it makes working with my monorepo much less chaotic. It would be great if you could apply a different theme based on the regex. For me, it's more "in-your-face" and really would make it obvious where I am in my monorepo.  I find the stark separation really helpful so I can look at any place in the window instead of glancing up at the top of the screen.

**Comment by oreporan** [comment]
Hey, Thanks for the  5x⭐️ on VS marketplace :)

Concerning the theme, that could be done, I'll look to see what implications that might have.

**Comment by nate-whil** [comment]
Hey @oreporan I've given this some thought and I think it's not practical. vsCode doesn't support two themes in the same window, and if you have a split view and one file is in /native and the other is in /web both files will need to have the same theme because of the constraints of vscode. If focusing one file changes the theme of every file, it kind of defeats the purpose of this feature. Closing.
