### ISSUE TITLE
Use of Relative Path?

### ISSUE THREAD

**Issue by minig0d** [oreporan/color-tabs-vscode#33]
So this one baffled me for a while... couldn't figure out why the extension wasn't working for me then skimmed the code and I think the culprit is it's looking at the relative path of the open file?  If so, would it be possible to look at the full path?

For example (on windows) if I have all of Project A mapped to my T drive, and all project B mapped to my V drive then the following regex won't work:
 `"regex": "^[vV].*", `

**Comment by oreporan** [comment]
So, originally it was the full path, but after #21 I decided that looking at the full-path was irrelevant, and the regex should be based starting from the root from the project.

I think its just a matter of the focus of the plugin, I see it as per-file coloring of the same project

**Comment by minig0d** [comment]
Same focus... differentiate the files.  :)

Completely understand not wanting to build out additional functionality but seems silly to limit the benefit to a specific use case and cut down the potential audience who can benefit

**Comment by oreporan** [comment]
Looks like you want to differentiate an entire project, not files inside a project.

Looks like you want something like this:

`/Users/ore/projects/projectA/someDir/someFile.js` -> `red`
`/Users/ore/projects/projectB/someDir/someFile.js` -> `green`

while this plugin is for:
`/Users/ore/projects/projectA/someDirA/someFile.js` -> `red`
`/Users/ore/projects/projectA/someDirB/someFile.js` -> `green`

I would suggest for you to maybe use something like [peackock](https://github.com/johnpapa/vscode-peacock) if you want each vscode instance to be a different color

**Comment by minig0d** [comment]
I don't have multiple instances.  Just multi-root workspace so it HAS to be a plugin like this until vscode allows folder-specific settings.

**Comment by oreporan** [comment]
I don't mind adding a configuration for it if it helps you out.
If you do the PR I'll add this option

**Comment by minig0d** [comment]
Sorry I've been super tied up with work... just did some digging on this...  The one thing I didn't realize was that the asRelativePath change actually considers the "name" of the folder as the first part of the path.  I thought the name label was just a UI facing thing, and the physical folder name was actually being resolved.  IE there is no extension change needed to accomplish what I was trying to do (although I would definitely recommend adding a little bit to the documentation and the help text about what is actually being referenced).

I'm not sure if there is a way to add the "name" to the workspace.json through the UI, but just to help anyone else with similar issues: if you edit the workspace.json file (F1 > "Workspaces: Open Workspace Configuration File") you can add a "name" to the path which both shows up in the UI and is matched on with the regex.  So whereas previously two identically named folders named "Test" would have shown up, changing to the following works perfectly to match against.
```
	"folders": [
        {
            "name": "DEV",
            "path": "C:\\Test"
        },
        {
            "name": "PROD",
            "path": "D:\\Test"
        }
    ]
```

And then just whatever your regex pattern in the extension config:
```
    "colorTabs.config": [
        {
            "regex": "^DEV.*",
            "label": "*** DEV SERVER ***",
            "color": "green"
        },
        {
            "regex": "^PROD.*",
            "label": "*** CAUTION: PRODUCTION SERVER *** ",
            "color": "red"
        }
    ]
```

**Comment by oreporan** [comment]
nice. I wasn't even aware of the `folders` config in the workspace settings
