### ISSUE TITLE
use user settings instead of workbench

### ISSUE THREAD

**Issue by naume** [oreporan/color-tabs-vscode#34]
Hi is it possible to change this https://github.com/oreporan/color-tabs-vscode/blob/master/src/changeColors.ts#L16 to user settings enstead of using the workbench settings?

We're using this great plugin in a Monorepo with a bunch of projects and now with your plugin, we have the possibility to recognize in which project we are working, but our employee wants to add their own colors without checking it into the settings.json (where we can't use .gitignore) we need it for the setup.

**Comment by oreporan** [comment]
Hey, 
I think its a bit more complex than that.

Every time you click on a tab, I need to write the color in the `settings.json`, if I write that in the user settings instead of the workspace settings, it would mean that any other vscode instance you have open would all of a sudden become that color.

**Comment by oreporan** [comment]
Hey,
its a bit more complicated than that.

If I write the colors to the user settings, it would mean that all of your open vscode instance would become colored.
I'm not sure thats a side-effect that makes sense.

When you focus on another vscode instance it should be removed, but still that situation might be confusing

**Comment by naume** [comment]
Ok I got you, I have then to find a way to cleanup the additions of this plugin before commit every time :-(
maybe you can provide a kind of config of the plugin as a property like defaultSettings: "user|workbench" then we can add user on the vscode we wan't? whats about that?

**Comment by oreporan** [comment]
I believe its a bad idea for this plugin to write to the user settings.
I'd rather not have this option

**Comment by oreporan** [comment]
I believe its a bad idea for this plugin to write to the user settings.
I'd rather not have this option

**Comment by Timst** [comment]
Hi! I know you think it's a bad idea, but I think you should reconsider letting people decide. It's indeed very annoying to have to remove the changes made to the project settings every time I want to commit.
