### ISSUE TITLE
Only update workspace's settings.json if a color-tabs configuration is found

### ISSUE THREAD

**Issue by atoiv** [oreporan/color-tabs-vscode#35]
## Bug

It appears color-tabs will add an empty `"workbench.colorCustomizations": {}` declaration to the end of the workspace's settings file (`.vscode/settings.json`), if the file exists.

It probably shouldn't do that, in the basic scenario, where no plugin specific rules are defined (neither in current workspace nor in user settings).

## Problem

If you have multiple projects, some of them ones where you don't want to use the plugin, but where the workspace's settings file exists, and where it is added to version control, the bug results in an unwanted line in your settings file.

Worst part is, you can't get rid of the extra line, unless you disable the plugin.

**Comment by oreporan** [comment]
You're right, I've been delaying getting to fix that annoying issue.

**Comment by oreporan** [comment]
Published in `0.10.0`
Thanks for the input :)
