### ISSUE TITLE
Feature request: Option to use absolute path

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [oreporan/color-tabs-vscode#43]
Use case:
I tend to have projects cloned in different locations multiple times so that I can jump quickly between things without having to reinstall dependencies every time (+ possibly having to stash/pop work).

It would be awesome if I could use `color-tabs-vscode` to quickly identify whether I'm e.g. in `dev/project` or `tmp/project` - which obviously requires awareness of the parent directory.

**Comment by oreporan** [comment]
Check out this issue https://github.com/oreporan/color-tabs-vscode/issues/33

**Comment by s-h-a-d-o-w** [comment]
Thanks, Peacock is an alright solution, I suppose! (Would rather not declare it on a workspace level but hey... it works. :) )

**Comment by oreporan** [comment]
Was actually pointing out the solution someone suggested there, where they mix this library (ColorTabs) with folder names to get the result you want

**Comment by s-h-a-d-o-w** [comment]
That's still a workspace setting: "if you edit the workspace.json file (F1 > "Workspaces: Open Workspace Configuration File") you can add a "name" to the path"
