### ISSUE TITLE
Feature Request: GUI for specific file.

### ISSUE THREAD

**Issue by tmiecz** [oreporan/color-tabs-vscode#45]
I did some research, but couldn't find anything that would match what I'm looking for and this plugin is the closest, but not exactly what I had in mind, so I figured I'd make a recommendation:

Right click GUI on a specific tab would open a context menu with a custom option, example:

1. right click an open tab [  index.php  ]
2. menu shows ColorTabs menu item with subitems of few colors and "clear color" options
3. you click on the color and [  index.php  ] gets highlighted because a direct path to the file gets injected to the plugin settings

I'm sure even more people can find this plugin essential then.

**Comment by oreporan** [comment]
How is this?

https://github.com/oreporan/color-tabs-vscode/pull/46

**Comment by oreporan** [comment]
Fixed in #46 
Version 0.12.0
