### ISSUE TITLE
Feature Request: Introspect settings in multi-root project

### ISSUE THREAD

**Issue by Jared-Dev** [oreporan/color-tabs-vscode#48]
I've got a few distinct projects that have their own theme settings within the `.vscode/settings.json` file. It would be absolutely incredible if there was a way to take the settings from each of those and automatically use those settings if you haven't overridden them inside of a color tabs config file!

**Comment by oreporan** [comment]
Currently I don't override all the `colorCustomization` settings, I just append to them.
Do you mean that your settings are being overriden when using ColorTabs?

**Comment by Jared-Dev** [comment]
No, I guess I'm asking,...

1) if in a multi root workspace
2) look for color settings in the `.vscode` folder (multi root doesn't respect those currently)
3) apply those color settings
4) spend to those settings if they are defined in your config file

**Comment by oreporan** [comment]
Not too familiar with multi root
According to this I see settings are possible in multiroots?
https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by Jared-Dev** [comment]
They are for the whole project. The unfortunate thing is that if you want the theme for your frontend to have tabs be shown as red while the backend is shown in blue that isn't possible.

It looks like this would be possible to define the settings for your plugin I guess my main "ask" would be to see if you could infer the desired colors based on the default vscode settings file!

**Comment by Jared-Dev** [comment]
I just did some testing. It looks like the plugin gets locked into the first matching rule AFAIK

Depending on the order of the matching rules in `colorTabs.config` it'll write the settings in the `*.code-workspace` file.

After that, it won't update based on the currently selected file.

**Comment by oreporan** [comment]
Yes it works top-down
