### ISSUE TITLE
After ColorTabs extension is uninstalled, statusBar color remains

### ISSUE THREAD

**Issue by vivianliang** [oreporan/color-tabs-vscode#50]
After the ColorTabs extension is uninstalled, statusbar color remains (on all color themes that were tried with the extension on, but not others).
<img width="1224" alt="Screen Shot 2020-11-13 at 3 09 55 PM" src="https://user-images.githubusercontent.com/4467143/99129399-55e6bc00-25c2-11eb-858c-069d933908db.png">

The issue persists after uninstalling VS Code, wiping these things out, and reinstalling fresh 🤷🏻‍♂️:
```
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -fr ~/.vscode/
```

Update: Found the culprit. The `.vscode/settings.json` _within_ the code directory isn't cleaned up.

**Comment by oreporan** [comment]
Hi

There is a [known issue](https://github.com/microsoft/vscode/issues/45474) about running API commands on uninstall of a vscode plugin

**Comment by vivianliang** [comment]
Thanks, good to know. Thanks for the plug-in!

(By the way, if anyone runs into this in the future, manual cleanup of `.vscode/settings.json` in the workbench does the trick.)
