### ISSUE TITLE
Feature request : color the tab itself

### ISSUE THREAD

**Issue by paulalbertdev** [oreporan/color-tabs-vscode#51]
Hi ! 
First of all thank you for the work you've done, that's awesome !
I wanted to tell you that I've got another idea : Could there be an option to also color the tab itself ?
That way I could quickly visually identify an opened file following its directory or its extension, that would be awwwwesome ! 
Cheers
And keep up such a good work !

**Comment by paulalbertdev** [comment]
(maybe add the color as a percentage between the original color and the new one, so that it remains subtle ?)

**Comment by oreporan** [comment]
Hey, do you mean coloring the active tab instead of just its border?
Right now I am using `tab.activeBorder`. You can see the list [here](https://code.visualstudio.com/api/references/theme-color)
I could switch to `tab.activeBackground` but as you said, its quite strong on the eyes

**Comment by paulalbertdev** [comment]
I even mean coloring ALL tabs backgrounds, the aim would be to super quickly see the type or the parent folder, for example, of each opened file.
Yes it would be strong on the eyes, but it would be an option to activate or not, and the idea of the percentage of coloration would be here to make it a little more subtle.

**Comment by oreporan** [comment]
its currently not possible with vscode API to color in active backgrounds with some logic. 
They only allow these:

```
tab.inactiveBackground
tab.activeBackground
```

Meaning I can decide a single color for all inactive backgrounds

**Comment by paulalbertdev** [comment]
Ho I see, that's sad...
So my request isn't actually doable, even with borders, right ?
Then sorry for the disturbance, have a good day ;)

**Comment by oreporan** [comment]
afraid not
Sorry, enjoy the library :)
