### ISSUE TITLE
Sample of a C/C++ project, w/a multi-level source tree folder hierarchy?

### ISSUE THREAD

**Issue by davegi** [oreporan/color-tabs-vscode#56]
I was wondering if you had a current sample of a C/C++ project, w/a multi-level source tree folder hierarchy, configured w/ ColorTabs?
I cannot seem to get it configured such that it displays different color tabs, etc. for the different folders.
Thanks,
djg

**Comment by oreporan** [comment]
Hey @davegi 
The language of the project is irrelevant, as this extension only looks at file/directory names in order to color the tabs. 

Can you paste here the colortabs config you tried (from your `settings.json`)  and how does your project file tree look

for example:
```
    [
        {
            "regex": ".*\/web\/.*"
        },
        {
            "regex": ".*\/mobile\/.*"
        }
    ]
```
