### ISSUE TITLE
failed in Windows

### ISSUE THREAD

**Issue by davidzhu1989** [oreporan/color-tabs-vscode#6]
it can not work on Windows 10?

**Comment by oreporan** [comment]
Not that I know of, I have no real way of testing it on Window10
Can you tell me what error you see in the `output` part of vscode?

I can't think of a reason though, the API is very straightforward...

**Comment by oreporan** [comment]
Let me know what regex you're putting also please

**Comment by LesterCheng** [comment]
I have Win10 and it's working for me, you just need to make sure you're using backslashes in the regex for your path. 
e.g.:
"regex": ".\*\\\\mobile\\\\.\*"

**Comment by oreporan** [comment]
I'm gonna go ahead and close this since its a regex issue
