### ISSUE TITLE
Colour all tabs, not just the active one

### ISSUE THREAD

**Issue by NickiForte** [oreporan/color-tabs-vscode#60]
To my understanding, it is currently only possible to keep the thin coloured line (as in image below) 

![image](https://user-images.githubusercontent.com/95344621/166924943-3dea8f56-54ca-4b8c-a767-eb03f83eba80.png)

for the currently active tab. However, it would be extremely convenient if an option was included where this thin coloured line would be visible for all open tabs, not just the currently active one. Would this be possible to implement?

**Comment by oreporan** [comment]
Hey, this has been addressed #19  
At that point in time vscode API didn't allow coloring specific tabs that are open and in the background.
You have the ability to color all of the background tabs, but without any logic
