### ISSUE TITLE
Colorize the tab even if not active

### ISSUE THREAD

**Issue by LeonardoGentile** [oreporan/color-tabs-vscode#64]
Hello,
thank you very much for this!

Do you think it would be possible to apply a colorized border to the tabs, even if in that moment are not active (but opened)?
This would be very useful to identify a specific file when you have many opened tabs.

👍

**Comment by oreporan** [comment]
As of now this isn't possible. You can't change the color of a specific tab, you can only control the color of the active tab, and of all the inactive tabs (but they would all be mapped to a single color)

There is no such customization of `tab[i].color = 'green'`
