### ISSUE TITLE
feature: different terminal color should also be reflected

### ISSUE THREAD

**Issue by andreElrico** [oreporan/color-tabs-vscode#65]
First off all, thank you alot for this very good extention! (rated it 5 stars)

Another hickup im having with multi-root workspaces in vscode is having multiple terminals open for each project and mixing them up.

It would be great if its possible to additionally have to "terminal background filled" or at least the active terminal/ bash colored in the specified project color.

This would mean we could have 
+ file project A (red) open `AND` in terminal project B (yellow) open

**Comment by oreporan** [comment]
Hey, thanks :)

From a first look it seems possible, but could be kind of harsh on the eyes to color your terminal background bright red
Have any other suggestions?

all I see they give you is terminal.background and terminal.foreground (which is the text color)

**Comment by andreElrico** [comment]
maybe we could specify terminal.background and terminal.foreground in the colorTabs config to something that is pleasant for the eye.

also if possible we could change the background color of the bash-tabs

![image](https://user-images.githubusercontent.com/44729345/177308493-b5b0ea11-816b-42c3-93b9-9fc8cc15bb79.png)

it seems the vert-bar is already colored according to the currenty opened file but not respective terminal

**Comment by andreElrico** [comment]
Also an idea: change the naming would also help: bash of project A > project A (Bash)

in the colorTabs config
```
{
...
  terminalName: {
    from: ".*(bash).*"
    to: "Project A ($1)"
  }
}
```

anther Idea (if possible): If we can set the cursor fill-color according to project and the test-color behind the cursor.

**Comment by oreporan** [comment]
Sorry for the delay @andreElrico 

Closest one I found (without being too aggressive for the user) is this, let me know if you want it:

![image](https://user-images.githubusercontent.com/2146999/194004497-e5bfa5bc-5821-486e-ac11-9f849e43beaa.png)

**Comment by oreporan** [comment]
Feel free to look here https://code.visualstudio.com/api/references/theme-color#lists-and-trees
