### ISSUE TITLE
Support for tabless configs

### ISSUE THREAD

**Issue by binaryben** [oreporan/color-tabs-vscode#68]
This is a strange request, but could an option be added to add an icon next to the file title?

I have Code [set up to run without tabs](https://code.visualstudio.com/docs/getstarted/userinterface#_working-without-tabs) which means the only thing that can be styled is the status bar. Unfortunately this is conflicting with Peacock.

I'm imagining a possible solution would be to add a coloured dot next to the file name instead, similar to where git status indicators are added (A, M, etc)

**Comment by oreporan** [comment]
Hey @binaryben 
Thanks for the issue

I've done some investigation, Its indeed possible to change the color of the selected file in the explorer, but it would override the one color given by your github extension (A/M badges and their colors)

I'm not sure we want to override those... WDYT?

**Comment by oreporan** [comment]
Hey. @binaryben 

Since I don't want to override the colors given by the github extension (A/M) - What I propose is coloring the border of the selected file as such (orange in this example):

<img width="469" alt="image" src="https://user-images.githubusercontent.com/2146999/193829352-1e25ff9e-1e86-4026-9fa1-b3874f4b8222.png">


What do you think?

**Comment by binaryben** [comment]
Hmm, it’s an interesting idea @oreporan and I’d be glad to see at least something present in my IDE being able to be styled using this extension.

I was picturing the addition of an extra symbol along side the git symbols though rather than changing the colours of the git symbols (I agree, that would be terrible DX). Even just a small filled in circle as a simple indicator. 

Alternatively, maybe there is a way to change just the top border of the editor to simulate the tan underline when in tabless mode?

**Comment by oreporan** [comment]
Adding another colored symbol isn't available in their API. VScode allow adding another "badge" but the color affects the entire line.


[Here](https://code.visualstudio.com/api/references/theme-color#lists-and-trees) are the colors they support changing. The ones you're looking for are under _List and Trees_

The best one I could find is the the  `list.focusOutline`
