### ISSUE TITLE
Clarify backslash, leading .* or leading /

### ISSUE THREAD

**Issue by peter-lyons-kehl** [oreporan/color-tabs-vscode#71]
Thank you for this Ore. So helpful (both the extension and your feedback to other issues).

1. Unclarity about backslash in config regex
https://github.com/oreporan/color-tabs-vscode/blob/master/README.md mentions `"regex": ".*\/web\/.*"`. But VS Code: Ctrl+X (Extensions) > ColorTabs > wheel (mouseover tip "Manage") > Extension Settings > Workspace > Edit in settings.json generates an example regex without backslash: `"regex": ".*/web/.*"`. Please clarify if/when backslash is needed, and make both the doc and generated regex consistent.

2. If I don't need (or don't want) the regex to start with `.*`, does it match any substring of the (relative) file path, or does it match exactly the whole (relative) filepath (as if the regex were `^regex-here-as-set-in-config$`)? Please clarify in README.md.

3. From #33 I see that the file path being matched is not absolute, but relative (to the project root). Could you mention it somewhere in README.md (to save people's confusion, especially when they are troubleshooting), please?

4. Please document in README.md that, if matching a top-level directory (right under the workspace), the regex must not start with `/`, neither with `.*/` (as per #72.)

5. Could you mention in the docs that we do not need to restart VS Code after changing the config, and that it's automatically applied?

6. Then suggest to update the description on the MarketPlace, too.

**Comment by oreporan** [comment]
1. you're right, it was just a default example, but it should be ` ".*\/web\/.*"`
2. this is the regex that is run from the code:

```ts
const path = vscode.workspace.asRelativePath(e.document.fileName);
const map = config.find(mapping => new RegExp(mapping.regex, `g${ignoreCase ? 'i' : ''}`).test(path));
```

feel free to test against it..

3. Yeah I will add that 
4. I think thats obvious
5. As this is the first time it came up, not sure its needed
