### ISSUE TITLE
0.13.1 not compatible with latest vs code engine hence wont install

### ISSUE THREAD

**Issue by M0djO** [oreporan/color-tabs-vscode#76]
0.13.1 does not seem to be compatible with latest vs code engine hence wont install, leaving the extension stuck at v0.12.1, even if there is a newer version in the vs code extension marketplace.

Trying to install v0.13.1 manually gives the following error message in vs code:

"Unable to install extension 'orepor.color-tabs-vscode-ext' as it is not compatible with VS Code '1.79.2'."

**Comment by oreporan** [comment]
Hmm thats strange, I guess I dropped the `^` from the engine last time
Thanks
Fixed in version `0.14.1`
