### ISSUE TITLE
User settings automatically copied to workspace settings

### ISSUE THREAD

**Issue by HenryLie** [oreporan/color-tabs-vscode#8]
First of all, thank you for the great extension. I enjoy it very much!

However, I found an issue.
When this extension is active, it copies the content of `workbench.colorCustomizations` from user settings to workspace settings.
Every time I delete it, it will automatically get added again when focusing an editor tab.
I need to disable the extension now because the workspace settings file is pushed to the repository, and it will affect others.

**Comment by HenryLie** [comment]
Ah, I just realized something.
When the tab border color is changed, this extension adds `tab.activeBorder` property to workspace settings with the new tab color.

Is there a way to apply the color without writing to workspace settings?
If the workspace settings is not pushed to the repository it's fine, but in my case I need to push it...

**Comment by oreporan** [comment]
@HenryLie 
Thanks for the complements on the extension :)

As for your issue,
The only way to change colors is by adding/removing them from the workspace settings. Its similar to a themeing extension you would use.
I can't think of a way of doing it without writing to the settings as you mentioned.

May I ask why you need to push your settings in to the repo? What if other developers aren't using VScode at all?

**Comment by oreporan** [comment]
a small workaround would be for you to disable the tabColoring and only use the label feature of the extension, which adds your label to the title bar

Which was added here -
https://github.com/oreporan/color-tabs-vscode/pull/4

**Comment by HenryLie** [comment]
@oreporan Sorry, I missed your comments for some time.

On our team the workspace settings is shared to make it easier to share the necessary configurations for the project e.g. Flow and Eslint settings. We use different IDEs, but those IDEs will have their own configurations.

I understand now that this is the limitation of the API itself.
Thank you for the workaround. I prefer the tab border coloring since I use the IDE in fullscreen view (no titlebar present), but I guess it can't be helped. 
I'll keep using the extension for other projects, thanks! 👍

**Comment by maylortaylor** [comment]
This should be stated clearly somewhere in the github README or Docs.
I was fighting this for a while. I too work with people who don't use VsCode and don't want to see that folder/file show.

I hope VScode can update their APIs or something can change soon. I love this extension but can't use it at work :(

**Comment by oreporan** [comment]
@maylortaylor 
Can't you put `./vscode` in gitignore?

I'll update the docs anyway
