### ISSUE TITLE
Feature request: Allow activity bar color change

### ISSUE THREAD

**Issue by ybentz** [oreporan/color-tabs-vscode#9]
When working with a fullscreen editor the title bar is hidden (at least on a mac) so the only visible color change is the tab border. It would be great if the background color would also apply to the activity bar (or whatever else the user wants and is possible to change).

As a side note, this extension is awesome! Been looking for something like this for a while so thank you for building it.

**Comment by oreporan** [comment]
Hey, 
Its a good idea, actually I was thinking of moving the color from the title bar to the activity bar only. But I guess we can make it configurable...

**Comment by ybentz** [comment]
From a quick look at the code looks like it should be pretty simple to add any configurable theme part as a separate setting. I'll try to make a PR for it whenever I have the time.
